name: oscillatorDB
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2021.5.25=haa95532_1
  - certifi=2021.5.30=py38haa95532_0
  - dnspython=1.16.0=py38_0
  - openssl=1.1.1k=h2bbff1b_0
  - pip=21.1.2=py38haa95532_0
  - pymongo=3.11.4=py38hd77b12b_0
  - python=3.8.10=hdbf39b2_7
  - setuptools=52.0.0=py38haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
prefix: C:\Users\tatka\anaconda3\envs\oscillatorDB
